class FlaskTemplate:
    
    imports = 'from flask import Flask, jsonify\nfrom app import app'
    
    app = 'from flask import Flask\n\napp = Flask(__name__)'
    
    run = """import app\n\nif __name__ == '__main__': 
    app.run()"""
    
    routes = """# Home page
@app.route('/')
def home():
    return jsonify({
        'message': 'Welcome to this simple Flask API generated by API Generator',
        'author': 'Mazzya',
        'Github': 'https://www.github.com/Mazzya',
        'Github Project': 'https://github.com/Mazzya/API-Generator'
    })

# Add new product
@app.route('/products', methods = ['POST'])
def addProduct():
    pass

# Get all products
@app.route('/products')
def getProducts():
    pass

# Update product
@app.route('/products/<int:id>', methods=['PUT'])
def editProduct(id):
    pass

# Delete product
@app.route('/products/<int:id>', methods = ['DELETE'])
def deleteProduct(id):
    pass

# This function handles 404 error
@app.errorhandler(404)
def page_not_found(error):
    return jsonify({'message': 'page not found !'})"""